CREATE TABLE Person(
                       id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       username varchar(100) NOT NULL,
                       year_of_birth int NOT NULL,
                       password varchar NOT NULL
);
TRUNCATE TABLE Person;

ALTER TABLE Person ADD COLUMN role varchar(100) NOT NULL;

UPDATE Person set role='ROLE_ADMIN' WHERE id=7;